# The Docker image that will be used to build the app:
image: node:25-alpine

create-pages:
  pages:
    # The folder that contains the files to be exposed at the Pages URL:
    publish: public
  rules:
    # Ensures that only pushes to the default branch
    # will trigger a Pages deploy:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    # Run Steam data fetch script:
    - node public/js/steam-backend-fetch.js
